name: Mirror and run GitLab CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Mirror + trigger CI
      uses: tkf2019/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.tsinghua.edu.cn/os-lab/2024s/public/rcore-tutorial-test-2024s"
      env:
        GITLAB_HOSTNAME: "git.tsinghua.edu.cn"
        GITLAB_PROJECT_ID: "29101"
        GITLAB_PROJECT_NAME: "rcore-tutorial-test-2024s"
        GITLAB_PROJECT_TOKEN: ${{secrets.GITLAB_PROJECT_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
