[toolchain]
profile = "minimal"
# use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
channel = "nightly-2024-02-25"
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
targets = [
    "riscv64imac-unknown-none-elf",
    "riscv64gc-unknown-none-elf",
]
